global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'neurogate-monitor'

scrape_configs:
  - job_name: 'neurogate-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'neurogate'
          environment: 'dev'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
